const ALIAS_ATTRS           = ['strokeStyle', 'fillStyle', 'globalAlpha'];
const CAPITALIZED_ATTRS_MAP = {
  r            : 'R',
  opacity      : 'Opacity',
  lineWidth    : 'LineWidth',
  clip         : 'Clip',
  stroke       : 'Stroke',
  fill         : 'Fill',
  strokeOpacity: 'Stroke',
  fillOpacity  : 'Fill',
  x            : 'X',
  y            : 'Y',
  rx           : 'Rx',
  ry           : 'Ry',
  re           : 'Re',
  rs           : 'Rs',
  width        : 'Width',
  height       : 'Height',
  img          : 'Img',
  x1           : 'X1',
  x2           : 'X2',
  y1           : 'Y1',
  y2           : 'Y2',
  points       : 'Points',
  p1           : 'P1',
  p2           : 'P2',
  p3           : 'P3',
  p4           : 'P4',
  text         : 'Text',
  radius       : 'Radius',
  textAlign    : 'TextAlign',
  textBaseline : 'TextBaseline',
  font         : 'Font',
  fontSize     : 'FontSize',
  fontStyle    : 'FontStyle',
  fontVariant  : 'FontVariant',
  fontWeight   : 'FontWeight',
  fontFamily   : 'FontFamily',
  clockwise    : 'Clockwise',
  startAngle   : 'StartAngle',
  endAngle     : 'EndAngle',
  path         : 'Path',
  outline      : 'Outline',
  html         : 'Html'
};
const SVG_ATTR_MAP          = {
  opacity            : 'opacity',
  clip               : 'clip',
  stroke             : 'stroke',
  fill               : 'fill',
  strokeOpacity      : 'stroke-opacity',
  fillOpacity        : 'fill-opacity',
  strokeStyle        : 'stroke',
  fillStyle          : 'fill',
  x                  : 'x',
  y                  : 'y',
  r                  : 'r',
  rx                 : 'rx',
  ry                 : 'ry',
  re                 : 're',
  rs                 : 'rs',
  width              : 'width',
  height             : 'height',
  image              : 'href',
  x1                 : 'x1',
  x2                 : 'x2',
  y1                 : 'y1',
  y2                 : 'y2',
  lineCap            : 'stroke-linecap',
  lineJoin           : 'stroke-linejoin',
  lineWidth          : 'stroke-width',
  lineDash           : 'stroke-dasharray',
  miterLimit         : 'stroke-miterlimit',
  font               : 'font',
  fontSize           : 'font-size',
  fontStyle          : 'font-style',
  fontVariant        : 'font-variant',
  fontWeight         : 'font-weight',
  fontFamily         : 'font-family',
  startArrow         : 'marker-start',
  endArrow           : 'marker-end',
  preserveAspectRatio: 'preserveAspectRatio'
};
const ALIAS_ATTRS_MAP       = {
  stroke : 'strokeStyle',
  fill   : 'fillStyle',
  opacity: 'globalAlpha'
};
